### ISSUE TITLE
Studies addition suggestion

### ISSUE THREAD

**Issue by juliopovedacs** [Te-k/ipvtechbib#2]
Hi!

Thanks for your work. This is a great repository!

I suggest you to add the following studies as well:

- Yixin Zou, Allison McDonald, Julia Narakornpichit, Nicola Dell, Thomas Ristenpart, Kevin Roundy, Florian Schaub, and Acar Tamersoy. The Role of Computer Security Customer Support in Helping Survivors of Intimate Partner Violence. USENIX Security Symposium. 2021. https://nixdell.com/papers/USENIX_2021_IPV.pdf
- Strohmayer, A., Slupska, J., Bellini, R., Neff, G., Coventry, L., Hairson, A., Dodge, A. (2021) Trust and Abusability Toolkit: Centering Safety in Human-Data Interactions. https://nrl.northumbria.ac.uk/id/eprint/47508/1/TrustAndAbusabilityToolkit.pdf

Thanks.

Julio

**Comment by Te-k** [comment]
Thank you so much ! I'll have a look and add them this week

**Comment by juliopovedacs** [comment]
Great! You're welcome.

**Comment by Te-k** [comment]
I added them, forgot to mention it and close the ticket. Thanks !
